### ISSUE TITLE
getColumnsType returns empty columns as numbers

### ISSUE THREAD

**Issue by philipkueng** [nzzdev/Q-table#109]
The function [`getColumnsType()`](https://github.com/nzzdev/Q-table/blob/d2f07d867b6b6d63bad546187aecbced22bed30c/helpers/data.js#L29) returns empty columns (null) as numeric. This needs to be fixed.

**Comment by philipkueng** [comment]
I just implemented a check that empty columns wont be recognized as `numeric` columns in the `option-availability`. It's still possible to declare `minibars` when there are just 3 titles but just 2 columns filled with `data`.

This is because the following check:
```javascript
  if (item.data.table.length !== 0) {
        if (
          !item.options.cardLayout &&
          **item.data.table[0].length >= 3 &&**
          getNumericColumns(item.data.table).length > 0
        ) {
          isAvailable = true;
        }
      }
      return {
        available: isAvailable
      };
    }

```
I think it would more useful if we just check if the `getNumericColumns(item.data.table).length` would be `>2`. What do you think @manuelroth ?

**Comment by manuelroth** [comment]
Yes, I think this makes sense. Lets do it like this
